import { Theme } from '../types';

export const windows98Theme: Theme = {
  desktop: {
    background: '#008080',
  },
  window: {
    backgroundColor: '#c0c0c0',
    borderColor: '#000000',
    borderWidth: '2px',
    borderRadius: '0px',
    shadow: 'none',
    header: {
      height: '22px',
      backgroundColor: '#000080',
      textColor: '#ffffff',
      fontSize: '11px',
      fontWeight: 'normal',
      padding: '3px 6px',
    },
    button: {
      size: '18px',
      borderRadius: '0px',
      hoverBackground: '#c0c0c0',
      activeBackground: '#808080',
      closeColor: '#000000',
      closeHoverColor: '#ffffff',
      minimizeColor: '#000000',
      minimizeHoverColor: '#ffffff',
      maximizeColor: '#000000',
      maximizeHoverColor: '#ffffff',
    },
  },
  taskbar: {
    height: '30px',
    backgroundColor: '#c0c0c0',
    borderTop: '2px solid #808080',
    item: {
      backgroundColor: '#c0c0c0',
      hoverBackground: '#d4d0c8',
      activeBackground: '#808080',
      textColor: '#000000',
      fontSize: '10px',
      padding: '3px 10px',
      borderRadius: '0px',
    },
    startButton: {
      // Windows 98: Gray start button
      backgroundColor: '#c0c0c0',
      hoverBackground: '#d4d0c8',
      activeBackground: '#808080',
      textColor: '#000000',
      fontSize: '10px',
      fontWeight: 'normal',
      padding: '0 8px',
      borderRadius: '0px',
      minWidth: '80px',
      logoColors: {
        color1: '#000000', // Windows 98 logo black
        color2: '#808080', // Windows 98 logo gray
      },
    },
  },
  startMenu: {
    backgroundColor: '#c0c0c0',
    borderColor: '#000000',
    borderWidth: '2px',
    borderRadius: '0px',
    shadow: 'none',
    itemTextColor: '#000000',
    itemHoverBackground: '#000080',
    itemHoverTextColor: '#ffffff',
    itemPadding: '4px 20px 4px 10px',
    itemFontSize: '11px',
    minWidth: '200px',
  },
  folderTree: {
    itemTextColor: '#000000',
    itemHoverBackground: '#000080',
    itemHoverTextColor: '#ffffff',
    itemSelectedBackground: '#000080',
    itemSelectedTextColor: '#ffffff',
    itemPadding: '2px 6px',
    itemFontSize: '11px',
    indentSize: 16,
    expandIconColor: '#000000',
  },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#000000',
    borderWidth: '2px',
    borderRadius: '0px',
    textColor: '#000000',
    placeholderColor: '#808080',
    focusBorderColor: '#000080',
    disabledBackground: '#c0c0c0',
    disabledTextColor: '#808080',
    errorBorderColor: '#ff0000',
    checkColor: '#000000',
    checkBackground: '#ffffff',
    buttonBackground: '#c0c0c0',
    buttonHoverBackground: '#d4d0c8',
    buttonActiveBackground: '#808080',
    buttonBorderColor: '#000000',
    buttonTextColor: '#000000',
    buttonDisabledBackground: '#c0c0c0',
    buttonSecondaryBackground: '#e0e0e0',
    buttonSecondaryHoverBackground: '#d4d0c8',
    buttonDangerBackground: '#dc3545',
    buttonDangerHoverBackground: '#c82333',
    calendarBackground: '#ffffff',
    calendarHeaderBackground: '#c0c0c0',
    calendarDayHover: '#d4d0c8',
    calendarDaySelected: '#000080',
  },
};
